function rxnsToAdd = importExtraRxns(filename, dataLines)
%IMPORTFILE Import data from a text file
%  NONDENFEDADDRXNS = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a cell array.
%
%  NONDENFEDADDRXNS = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  nonDENFedaddRxns = importfile("/Users/clasenf/OneDrive - The Francis Crick Institute/Integration/GEM/Microbiome/nonDEN_Fed_addRxns.tab", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 28-Apr-2022 14:12:27

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["EX_M2B_C03465", "methyl2oxopentanoate2oxo3methylvalerate", "gut_to_blood_exchange"];
opts.VariableTypes = ["char", "char", "char"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["EX_M2B_C03465", "methyl2oxopentanoate2oxo3methylvalerate", "gut_to_blood_exchange"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["EX_M2B_C03465", "methyl2oxopentanoate2oxo3methylvalerate", "gut_to_blood_exchange"], "EmptyFieldRule", "auto");

% Import the data
nonDENFedaddRxns = readtable(filename, opts);

%% Convert to output type
nonDENFedaddRxns = table2cell(nonDENFedaddRxns);
numIdx = cellfun(@(x) ~isnan(str2double(x)), nonDENFedaddRxns);
nonDENFedaddRxns(numIdx) = cellfun(@(x) {str2double(x)}, nonDENFedaddRxns(numIdx));
end